import feedparser, re, validators

class FileHandler():
    
    def _format_entries(self, unstructred:dict):
        """
        Formats and strips entries created by Feedparser package to only contain:
        Title, Summary, Publishing date & Url

        Args:
            unstructred (dict): An unstructures entry generated by feedparser containing a whole lot of data

        Returns:
            dict: A dictionary containing the entry
        """
        structured = []
        for i in range(len(unstructred)):
            entry = dict()
            entry['title'] = unstructred[i].get('title','')
            entry['summary'] = unstructred[i].get('summary','')
            entry['pub_date'] = unstructred[i].get('published','')
            entry['url'] = unstructred[i].get('link','')
            structured.append(entry)
            
        return structured


    def process_rss_feeds(self, file_path:str = 'files/rss_feeds.txt'):
        """
        Processes rss/atom feeds with the help of the Feedparser package from a file of url's 

        Args:
            file_path (str, optional): The place where to read files from, needs to be a TXT file. Defaults to 'files/rss_feeds.txt'.

        Returns:
            list: A list of all feeds that have been processed
        """
        feeds = []
        with open(file_path, 'r') as file:
            length = len(file.readlines())
            file.seek(0)
            for feed in range(length):
                url = str(file.readline()).strip(".rss\n")
                f_dict = feedparser.parse(url)
                f_author = f_dict.feed.get('title',f_dict.feed.get('href', 'unnamed'))
                f_entries = f_dict.entries
                structured_feed_entries = self._format_entries(f_entries)
                feeds.append((f_author, structured_feed_entries))
                
        return feeds
            

    def txt_to_set(self, file_path:str = 'files/ignored_words.txt'):
        """
        Processes a TXT file and creates a set out of it which is then returned, split information by using RegEx: re.split('\s')

        Args:
            file_path (str, optional): The file path to the TXT file that needs to be converted to a set. Defaults to 'files/ignored_words.txt'.

        Returns:
            set: The set containing all the information from the provided file
        """
        set_of_file = set()
        sub_pattern = "\s"
        with open(file_path, 'r') as file:
            length = len(file.readlines())
            file.seek(0)
            for _ in range(length):
                line = str(re.sub(sub_pattern, '',str(file.readline())))
                set_of_file.add(line)
        return set_of_file

    
class FeedAggregator():
    
    def __init__(self):
        """
        Aggregates all rss/atom feeds from the given file and stores them in Feed() instances
        """
        self._rss_feed_list = FileHandler().process_rss_feeds()
        self._feeds = [Feed(feed, self) for feed in self._rss_feed_list]
        self._blacklisted = FileHandler().txt_to_set()
    
    
    @property
    def feed_list(self):
        """
        Read-only list of feeds

        Returns:
            list: List of all Feed() instances
        """
        return self._feeds
    
    
    @property
    def blacklisted(self):
        """
        Read-only set of all blacklisted words

        Returns:
            set: All blacklisted words read from a file
        """
        return self._blacklisted  
    
      
    @property
    def max_entries(self):
        """
        Read-only integer of max amount of Entry() instances found in a Feed() instance

        Returns:
            int: Highest number of Entry() instances found in one Feed() instance
         """
        if self._feeds == []:
            return
        feed_entries = set()
        for feed in self._feeds:
            feed_entries.add(len(feed.entries))
        return max(feed_entries)
    
    
    def popular_entries(self, filter_treshold:float = 0.01, entry_treshold:float = 0.01):
        """
        Gathers a list of all Entry() instances that fall above the treshold provided

        Args:
            filter_treshold (float, optional): Treshold with which the filters are gathered. Defaults to 0.01.
            entry_treshold (float, optional): Treshold with which the entries are gathered. Defaults to 0.01.

        Returns:
            list: List of all Entry() instances
        """
        popular_entries = []
        filters = dict()
        for feed in self._feeds:
            filters = feed.popular_words(self._blacklisted,filter_treshold, filters)

        for feed in self._feeds:
            popular_entries += feed.popular_entries(filters, entry_treshold)

        return popular_entries
    
    
    def __str__(self):
        """
        Displays all Feed() instances contained by this instance

        Returns:
            str: Fancy way to display what this instance holds
        """
        feed_coll = ''
        for feed in self._feeds:
             feed_coll = f"{feed_coll} {str(feed)} \n"
        return feed_coll
   
    
class Feed():

    def __init__(self, feed:tuple, aggregator:FeedAggregator):
        """
        Initialises a Feed() instance and adds every entry belonging to the feed in the form of an Entry() instance

        Args:
            feed (tuple): The feed contains (name of news org, entries)
            aggregator (FeedAggregator): The aggregator this Feed() instance belongs to
        """
        title, entries = feed
        self._name = title
        self._entry_list = []
        self._feed_aggregator = aggregator
        
        
        for entry in entries:
            self._entry_list.append(Entry(feed=self, **entry))
        
          
    @property
    def entries(self):
        """
        Read-only list of entries

        Returns:
            list: List of Entry() instances
        """
        return self._entry_list
    
    
    @property
    def weight(self):
        """
        Weight of Feed() instance in relation to all Feed() instances belonging to the FeedAggregator() instance. The normalization process takes the highest amount of entries found and divides it by the currents feed entries to generate a more balanced picture of how many times a word is featured in all feeds.

        Returns:
            float: The weight assigned to ever Entry() instance of this Feed() instance
        """
        if self._entry_list and self._feed_aggregator.max_entries != 0:
            return ((self._feed_aggregator.max_entries / len(self._entry_list)) / 100)
        return .01
        
    
    
    def popular_words(self, blacklisted,treshold:float = 0.1, popular_words:dict =dict()):
        """
         Scans all the articles and determines the populartiy of a given word according to how many times it features. Normalizes the occurence by giving each feed it's own weight. 

        Args:
            blacklisted (set): Set of blacklisted words
            treshold (float, optional): Treshold for below which words are omitted from the returned dictionary. Defaults to 0.1.
            popular_words (dict, optional): Applicable for a FeedAggregator() instance with multiple Feed() instances, passes along existing dictionary of popular words if entered. Defaults to dict().

        Returns:
            dict: Dictionary of popular words and their weight
        """
        _popular_words = popular_words
        for entry in self._entry_list:
            nouns = entry.filtered_words(blacklisted)
            for noun in nouns:
                _popular_words[noun] = round((_popular_words.get(noun, 0.00) + self.weight), 2)
        _popular_words = { word: weight for word, weight in _popular_words.items() if weight > treshold}
        
        return _popular_words
    
    
    def popular_entries(self, filters:dict, treshold:float = 0.01):
        """
        Assigns weight to entries according to the weight of filter words found in an entry. Returns all entries that have a weight that is above the treshold.

        Args:
            filters (dict): Words that entries need to be filtered by
            treshold (float, optional): Treshold that entry weight needs to be above, else is omitted from the returned list. Defaults to 0.01.

        Returns:
            list: A list of all filtered entries with weight above the treshold
        """
        _popular_entries = dict()
        for entry in self._entry_list:
            _weight = 0
            for word, weight in filters.items():
                if word in entry.summary.lower():
                    _weight += weight     
            _popular_entries[entry] = _weight
    
        return [entry for entry, weight in _popular_entries.items() if weight > treshold]
    
    
    def __str__(self):
        """
        Name of Feed() instance

        Returns:
            str: Name of Feed() instance
        """
        return f"{self._name} "
    

class Entry():
    
    def __init__(self, title:str, summary:str, pub_date:str, url:str, feed:Feed):
        """
        Creates an Entry() instance to be used by Feed() instances 

        Args:
            title (str): Title of the entry
            summary (str): Summary of the entry
            pub_date (str): Publishing date of the entry
            url (str): Url for the entry
            news_org (Feed): The Feed() instance this entry belongs to
        """
        self._title = title
        self._summary = summary
        self._pub_date = pub_date
        self._url = url
        self._feed = feed
        
        
    @property
    def title(self):
        """
        Read-only title
        
        Returns:
            str: The title of the Entry() instance
        """
        return self._title
        
        
    @property
    def summary(self):
        """
        Read-only summary

        Returns:
            str: The summary of the Entry() instance
        """
        return self._summary
    
    
    @property
    def pub_date(self):
        """
        Read-only publishing date

        Returns:
            str: The publishing date of the Entry() instance
        """
        return self._pub_date
    
    
    @property
    def url(self):
        """
        Read-only url

        Returns:
            str: The url of the Entry() instance
        """
        return self._url
    
    
    @property
    def feed(self):
        """
        Read-only feed

        Returns:
            str: The name of the Feed() instance this Entry() instance belongs to
        """
        return str(self._feed)
    
    
    def _word_validation(self, word:str, blacklisted:set , extra_blacklisted:set = {'href=', '<a>', '</a>','>', '<', 'www', 'http', 'https', 'rel='}):
        """
        Checks whether a word is valid, does so by using the validators module to check whether it is a url or domain. Also checks against a list of blacklisted words and takes an optional argument for custom blacklisted words or combinations.
        
        Args:
            word (str): The word that needs to be checked
            blacklisted (set): Set of predetermined words that are blacklisted
            extra_blacklisted (set): Optional additions to blacklisted words

        Returns:
            Boolean: Returns False if word has not passed validation, True if it does
        """
        stripped_word = word.lower()
        if stripped_word in blacklisted or stripped_word in extra_blacklisted:
            return False
        elif validators.url(stripped_word) is True or validators.domain(stripped_word) is True:
            return False
        return True


    def _find_nouns(self, blacklisted:set):
        """
        Tries to identify and collect nouns, does this by looking for capitalized words. By checking if the previous word is also capitalized it tries to combine words to form nouns. Also checks against blacklisted words to ignore.

        Args:
            blacklisted (set): Line to check for nouns

        Returns:
            list: List of potential nouns
        """
        split_line = self.summary.split(' ')
        combined_word = ''
        combined_words = []
        pattern = '[A-Z][^A-Z]*'
        for i in range(len(split_line)):
            sub_pattern = "[,]|[.][a-z]*|['’][a-z]"
            word = re.sub(sub_pattern, '',split_line[i])
            if self._word_validation(word, blacklisted) is False:
                continue
            if re.match(pattern, word) and combined_word == '':
                combined_word += word.lower()
            elif re.match(pattern, word) and re.match(pattern, split_line[max(i-1, 0)]):
                combined_word += f" {word.lower()}"
            elif combined_word != '' and re.match(pattern, word) is None:
                combined_words.append(combined_word)
                combined_word = ''
        return combined_words
        
        
    def filtered_words(self, blacklisted:set):
        """
        Returns a list of filtered words (potential nouns) that have been found in the Entry() instance

        Args:
            blacklisted (set): Set of words to ignore

        Returns:
            list: List of filtered words (nouns)
        """
        return self._find_nouns(blacklisted)
    